### ISSUE TITLE
Add MUcomplete support

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip-integ#10] opened 2020-02-25 21:16 UTC
Is it possible to implement MUcomplete support? Is a minimalist autocompletion plugin.
MUcomplete [already supports](https://github.com/lifepillar/vim-mucomplete/blob/f13357964cc074d4fe747787065bfb19046f7fce/doc/mucomplete.txt#L146) Neosnippet, SnipMate and UltiSnips.

**Comment by hrsh7th** [comment] 2020-02-26 00:14
I will try to support mucomplete.

**Comment by Shatur95** [comment] 2020-02-26 00:14
It would be nice!

**Comment by hrsh7th** [comment] 2020-02-26 01:49
@Shatur95 
Could you try https://github.com/hrsh7th/vim-vsnip-integ/commit/dd14a706b8eea6da3364ce78f75661d2fb46c5d8?

You can below setting to enable vsnip source on mucomplete.

```
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
\ 'default' : ['vsnip', 'path', 'omni', 'keyn', 'dict', 'uspl'],
\ 'vim'     : ['vsnip', 'path', 'cmd', 'keyn']
\ }
```

**Comment by Shatur95** [comment] 2020-02-26 08:57
Tested it, but it does not seems to work:
[![asciicast](https://asciinema.org/a/lvGiTL04MFWBL1NkyJeL1pvmJ.svg)](https://asciinema.org/a/lvGiTL04MFWBL1NkyJeL1pvmJ)

I configured [native neovim lsp](https://github.com/neovim/nvim-lsp) with the following config:
```lua
nvim_lsp.pyls.setup{
      capabilities = {
      textDocument = {
        completion = {
          completionItem = {
            snippetSupport = true
          }
        }
      }
    },
    init_options = {
      usePlaceholders = true,
      completeUnimported = true
    }
}
```

**Comment by hrsh7th** [comment] 2020-02-26 09:41
Ah, I got it now.
I was mistaken your mean.

My implemented feature is `snippet completion` but not implemented `Snippet expansion after CompleteDone`.

We can't implement the feature in currently nvim-lsp's omnifunc because it does not provide user_data.

Hm.... I will try create PR to neovim...><

**Comment by Shatur95** [comment] 2020-02-26 10:01
It would be awesome!
But the readme [says](https://github.com/hrsh7th/vim-vsnip-integ#deoplete-lsp) that [deoplete-lsp](https://github.com/Shougo/deoplete-lsp) `support textEdit/additionalTextEdits at CompleteDone`. Is it not the same?

By the way, thanks for the `snippet completion` implementation.

**Comment by hrsh7th** [comment] 2020-02-26 10:04
`deoplete-lsp` is not `nvim-lsp`.

Maybe you using `deoplete-lsp`?
Could you paste your vimrc's plugins section?

**Comment by Shatur95** [comment] 2020-02-26 10:10
> deoplete-lsp is not nvim-lsp.

But the deoplete-lsp readme says:
```
Install LSP enabled neovim(version 0.5.0+)
Install the latest deoplete
Install and configure nvim-lsp
```
So, if I understood corretcly, `deoplete-lsp` uses `nvim-lsp`.

> Maybe you using deoplete-lsp?

No, no, I definitely use `MUcomplete`, just trying to understand how `deoplete-lsp` (which, if I understood correctly, uses` nvim-lsp`) supports it.

**Comment by hrsh7th** [comment] 2020-02-26 10:18
Yes. deoplete-lsp uses nvim-lsp.
But deoplete-lsp adding custom user_data by itself.

https://github.com/Shougo/deoplete-lsp/blob/master/rplugin/python3/deoplete/source/lsp.py#L103

nvim-lsp's omnifunc and vsnip integration worked well in my local machine now.
I will create PR for nvim repo... but I don't know it will be merged.

**Comment by Shatur95** [comment] 2020-02-26 10:35
Thanks for the explanation :)
Will wait for your PR, hope it will be merged!

I also have another question about it. `MUcomplete` already have implementation for other snippet plugins built-in. So, is I opened the issue in the right place? Maybe I need to send `vsnip` integration request to the `MUcomplete` itself (after your PR to `neovim`)? This will allow to use `MUcomplete` with `vsnip` directly without extra plugin.

**Comment by hrsh7th** [comment] 2020-02-26 10:41
IMO, the below cases are both correct.

- Vsnip's snippet completion implemented in `vim-vsnip-integ`.
- Vsnip's snippet completion implemented in `MUcomplete`.

**Comment by Shatur95** [comment] 2020-02-26 10:56
Is the second approach will allow to use `vsnip` with `MUcomplete without the `vim-vsnip-integ`?

**Comment by hrsh7th** [comment] 2020-02-26 10:58
Yes. The second approach needs `vim-vsnip` and `MUcomplete` only.
But if we support snippet expantion after `CompleteDone` it needs `vim-vsnip-integ`.

**Comment by hrsh7th** [comment] 2020-02-26 11:05
I've sent PR to neovim.
https://github.com/neovim/neovim/pull/11949

**Comment by Shatur95** [comment] 2020-02-26 11:09
Thank a lot for fast response and explanations. So, the issue in the right place, I think :)

**Comment by Shatur95** [comment] 2020-03-01 15:27
I noticed mapping conflict with MUcomplete. If I using [this](https://github.com/hrsh7th/vim-vsnip#2-setting) configuration it conflicts with MUcomplete's switching between completions (via `<Tab>`). Is it possible to avoid it?

**Comment by hrsh7th** [comment] 2020-03-01 15:31
MUcomplete has https://github.com/lifepillar/vim-mucomplete/blob/master/plugin/mucomplete.vim#L26 setting.

You can avoid MUcomplete's default mapping.

and you can map your favorite key.

**Comment by Shatur95** [comment] 2020-03-01 15:36
Yes, I meant is it possible to use the same key (`<Tab>`, for example) for completion navigation when suggestions are visible and `vsnip-jump-next` when snip is available? Sorry for such newbie questions.

**Comment by hrsh7th** [comment] 2020-03-01 15:59
I don't recommend to use the same key.

But you can use the below setting maybe.

```viml
imap <expr><Tab> pumvisible() ? "\<Plug>(MUcompleteFwd)" : (vsnip#available(1) ? "\<Plug>(vsnip-expand-or-jump)" : "\<C-n>")
```

**Comment by Shatur95** [comment] 2020-03-01 16:13
Thank you!

**Comment by Shatur95** [comment] 2020-03-02 09:46
I found an issue with MUcomplete. Custom (non-LSP) snippets are not expanded. Tested with example from `README.md`:
[![asciicast](https://asciinema.org/a/kS5l05p01Ugf8YqSaBeC016Qx.svg)](https://asciinema.org/a/kS5l05p01Ugf8YqSaBeC016Qx)

**Comment by hrsh7th** [comment] 2020-03-02 09:56
It's expected behavior.
You shoud press Tab once more.

**Comment by Shatur95** [comment] 2020-03-02 10:04
Oh, I need to expand it, thank you, sorry for bothering.

**Comment by hrsh7th** [comment] 2020-03-02 10:10
Hm... Probably we can implement automatic expansion.
I try to implement it for trial.
If it's useful, I merge master it as optional maybe.

**Comment by Shatur95** [comment] 2020-03-02 10:12
It would be nice.

**Comment by hrsh7th** [comment] 2020-03-02 10:19
I don't think it is useful but anyway implemented in https://github.com/hrsh7th/vim-vsnip-integ/pull/14/files.

**Closed** 2020-06-04 07:54 UTC
Labels: waiting
